sudo: required
language: csharp
solution: NameSorter/name-sorter.sln
mono: none
dotnet: 2.2.100
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test NameSorter.nUnitTests/NameSorter.nUnitTests.csproj
notifications:
  email: false
