sudo: required
language: csharp
solution: NameSorter/name-sorter.sln
mono: latest
dotnet: 6.0.310
script:
  - dotnet restore 
  - dotnet build
  - dotnet test NameSorter.nUnitTests/NameSorter.nUnitTests.csproj
notifications:
  email: false
