language: csharp
solution: NameSorter/name-sorter.sln
mono: none
dotnet: 6.0.16

install:
- dotnet restore 

script:
-dotnet build
-dotnet test NameSorter.nUnitTests/NameSorter.nUnitTests.csproj

notifications:
	email: false
